In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df_1 = pd.read_csv(os.path.join("Вариант", "Серия_2", "FMWY.txt"), index_col=0)
df_1 = df_1.rename(columns={'X': 'X_0', 'Y': 'Y_0', "Z": "Z_0"})
df_1.index = pd.to_datetime(df_1.index)
df_1

                              X_0           Y_0         Z_0
DATE_TIME
2024-06-14 13:17:19  53030.695157  75477.529368  586.572412
2024-06-14 13:17:34  53030.534437  75477.530158  585.801767
2024-06-14 13:17:49  53030.677618  75477.506348  586.045204
2024-06-14 13:18:04  53030.653772  75477.576109  586.152136
2024-06-14 13:18:19  53030.675407  75477.579097  586.451804
...                           ...           ...         ...
2024-06-14 13:41:34  53030.733351  75477.430738  586.453832
2024-06-14 13:41:49  53030.569761  75477.462237  586.470182
2024-06-14 13:42:04  53030.606050  75477.537147  586.314052
2024-06-14 13:42:19  53030.647889  75477.480978  586.007804
2024-06-14 13:42:34  53030.633398  75477.549207  586.287536

[92 rows x 3 columns]

In [3]:
df_2 = pd.read_csv(os.path.join("Вариант", "Серия_2", "CLGK.txt"), index_col=0)
df_2 = df_2.rename(columns={'X': 'X_1', 'Y': 'Y_1', "Z": "Z_1"})
df_2.index = pd.to_datetime(df_2.index)
df_2

                              X_1           Y_1         Z_1
DATE_TIME
2024-06-14 13:15:04  66336.091690  87314.355330  379.717756
2024-06-14 13:15:19  66336.073167  87314.345732  379.784066
2024-06-14 13:15:34  66336.106298  87314.335218  379.939737
2024-06-14 13:15:49  66336.092880  87314.350315  379.733445
2024-06-14 13:16:04  66336.081675  87314.340662  379.636690
...                           ...           ...         ...
2024-06-14 13:41:19  66336.152776  87314.380851  379.909744
2024-06-14 13:41:34  66336.136521  87314.340024  379.822401
2024-06-14 13:41:49  66336.134645  87314.365586  380.055278
2024-06-14 13:42:04  66336.149950  87314.371251  379.757785
2024-06-14 13:42:19  66336.132988  87314.369910  379.700320

[100 rows x 3 columns]

In [4]:
df_3 = pd.concat([df_1, df_2], axis=1).dropna()
df_3

,X_0,Y_0,Z_0,X_1,Y_1,Z_1
DATE_TIME,,,,,,
2024-06-14 13:17:19,53030.695157,75477.529368,586.572412,66336.126939,87314.371078,379.468692
2024-06-14 13:17:34,53030.534437,75477.530158,585.801767,66336.148269,87314.378548,379.852752
2024-06-14 13:17:49,53030.677618,75477.506348,586.045204,66336.110548,87314.363415,379.776426
2024-06-14 13:18:04,53030.653772,75477.576109,586.152136,66336.148893,87314.380147,379.803501
2024-06-14 13:18:19,53030.675407,75477.579097,586.451804,66336.138624,87314.349575,379.351513
...,...,...,...,...,...,...
2024-06-14 13:41:04,53030.643002,75477.493353,586.299537,66336.080809,87314.358944,379.561579
2024-06-14 13:41:34,53030.733351,75477.430738,586.453832,66336.136521,87314.340024,379.822401
2024-06-14 13:41:49,53030.569761,75477.462237,586.470182,66336.134645,87314.365586,380.055278
2024-06-14 13:42:04,53030.606050,75477.537147,586.314052,66336.149950,87314.371251,379.757785
2024-06-14 13:42:19,53030.647889,75477.480978,586.007804,66336.132988,87314.369910,379.700320

In [5]:
df_3.loc[:, 'dX'] = df_3["X_1"] - df_3["X_0"]
df_3.loc[:, 'dY'] = df_3["Y_1"] - df_3["Y_0"] 
df_3.loc[:, 'dZ'] = df_3["Z_1"] - df_3["Z_0"]

In [6]:
df_4 = df_3[["dX", "dY", "dZ"]]
df_4

                               dX            dY          dZ
DATE_TIME
2024-06-14 13:17:19  13305.431782  11836.841710 -207.103720
2024-06-14 13:17:34  13305.613832  11836.848391 -205.949015
2024-06-14 13:17:49  13305.432930  11836.857066 -206.268778
2024-06-14 13:18:04  13305.495120  11836.804038 -206.348635
2024-06-14 13:18:19  13305.463217  11836.770478 -207.100291
...                           ...           ...         ...
2024-06-14 13:41:04  13305.437806  11836.865590 -206.737958
2024-06-14 13:41:34  13305.403170  11836.909286 -206.631431
2024-06-14 13:41:49  13305.564884  11836.903349 -206.414903
2024-06-14 13:42:04  13305.543900  11836.834104 -206.556267
2024-06-14 13:42:19  13305.485098  11836.888931 -206.307485

[81 rows x 3 columns]

In [7]:
df_4 = df_3[["dX", "dY", "dZ"]]
df_4.loc[:, 's_dist'] = (df_4["dX"] ** 2 + df_4["dY"] ** 2 + df_4["dZ"] ** 2) ** 0.5
df_4.loc[:, 'azimuth'] = np.degrees(np.arctan2(df_4['dY'], df_4['dX']))
df_4.loc[:, 'zenith'] = np.degrees(np.arccos(df_4['dZ'] / df_4['s_dist']))

/var/folders/c2/pfk652nd5r30mk7t_rz17pg00000gn/T/ipykernel_25020/3513088829.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.loc[:, 's_dist'] = (df_4["dX"] ** 2 + df_4["dY"] ** 2 + df_4["dZ"] ** 2) ** 0.5
/var/folders/c2/pfk652nd5r30mk7t_rz17pg00000gn/T/ipykernel_25020/3513088829.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.loc[:, 'azimuth'] = np.degrees(np.arctan2(df_4['dY'], df_4['dX']))
/var/folders/c2/pfk652nd5r30mk7t_rz17pg00000gn/T/ipykernel_25020/3513088829.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4.loc[:, 'zenith'] = np.degrees(np.arccos(df_4['dZ'] / df_4['s_dist']))

In [8]:
dsc = df_4.describe().loc[["mean", "std"]][["s_dist", "azimuth", "zenith"]]
dsc

            s_dist    azimuth     zenith
mean  17809.797069  41.657046  90.664352
std       0.062983   0.000187   0.001039

In [9]:
dsc.loc[["std"]] = dsc.loc[["std"]].apply(lambda row: row / (len(df_4) ** 0.5), axis=1)
dsc

            s_dist    azimuth     zenith
mean  17809.797069  41.657046  90.664352
std       0.006998   0.000021   0.000115

In [10]:
dsc.loc["std", "azimuth"] = dsc.loc["std", 'azimuth'] * 3600
dsc.loc["std", "zenith"] = dsc.loc["std", "zenith"] * 3600
dsc

            s_dist    azimuth     zenith
mean  17809.797069  41.657046  90.664352
std       0.006998   0.074949   0.415404

In [11]:
azimuth = dsc.loc["mean", 'azimuth']
dsc.loc["mean", "azimuth"] = azimuth + 360 if azimuth < 0 else azimuth
dsc

            s_dist    azimuth     zenith
mean  17809.797069  41.657046  90.664352
std       0.006998   0.074949   0.415404